# C files
C_SRC=loba.c tribal.c

# ISPC files
ISPC_SRC=tribal.ispc

# ISPC targets
ISPC_TARGETS=avx

# Program name
EXE=main

# Floating point type
REAL=double

# Debug version
DEBUG=yes

# Do the rest
include common.mk
